#   Copyright (c) 2021  Thiago Lopes da Silva
 
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
 
#       http://www.apache.org/licenses/LICENSE-2.0
 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Stage 1: Build the base code. 
FROM node:14.17.0-alpine as buildStage

LABEL stage="builder"

WORKDIR /app

COPY . /app

RUN [ "yarn" ]

RUN [ "yarn", "build" ]

RUN ["rm", "-rf", "node_modules"]

RUN [ "yarn", "--production" ]

# Stage 2. Run build container code using the code from buildStage phase.
FROM node:14.17.0-alpine
LABEL author="Thiago lopes da Silva<thiagoolsilva@gmail.com>"

RUN apk update && apk add bash

WORKDIR /app

RUN addgroup -S container-group && adduser -S container-user -G container-group

USER container-user

COPY --from=buildStage /app/dist/ /app/
COPY --from=buildStage /app/node_modules/ /app/node_modules

CMD [ "node", "src/index.js" ]